export const List = {
    amount: 10,
    data: [
    {
      id: 1,
      name: "Royaltea",
      address: "Quận Long Biện",
      type: "Món Miền Bắc",
      category: "Café/Dessert",
    },
    {
      id: 2,
      name: "Pepperonis Pizza",
      address: "Quận Hà Đông",
      type: "Món Âu",
      category: "Nhà hàng",
    },
    {
      id: 3,
      name: "Domino's Pizza",
      address: "Quận Ba Đình",
      type: "Món Việt" || "Món Âu" || "Châu Mỹ",
      category: "Nhà hàng",
    },
    {
      id: 4,
      name: "Crepes K - Bánh Crepe",
      address: "Quận Đống Đa",
      type: "Món Bắc" || "Món Miền Trung",
      category: "Tiệm bánh",
    },
    {
      id: 5,
      name: "Thái Hạnh - Huy Mai - Quán Ăn Vặt - Ngõ 4C",
      address: "Quận Đống Đa",
      category: "Ăn vặt/vỉa hè" || "Quán ăn",
      type: "Món Miền Nam",
    },
    {
      id: 6,
      name: "Grille6 - Salad, Steak & Pasta - Hào Nam",
      address: "Quận Đống Đa",
      type: "Đông Âu",
      category: "Nhà hàng",
    },
    {
      id: 7,
      name: "Bánh Mì Cô Long - Nguyễn Chí Thanh",
      address: "Quận Ba Đình",
      type: "Món Việt",
      category: "Ăn vặt/vỉa hè",
    },
    {
      id: 8,
      name: "Cafe Giảng - Cafe Trứng",
      address: "Quận Hoàn Kiếm",
      type: "Món Việt",
      category: "Café/Dessert",
    },
    {
      id: 9,
      name: "Xôi Yến - Trần Hưng Đạo",
      address: "Quận Hoàn Kiếm",
      type: "Món Việt",
      category: "Ăn vặt/vỉa hè",
    },
    {
      id: 10,
      name: "Gà Rán Popeyes - Mac Plaza",
      address: "Quận Hà Đông",
      type: "Quốc tế",
      category: "Quán ăn",
    },
  ],
};
